### ISSUE TITLE
Utilize multiple types or references from json or xsd schema within RAML document

### ISSUE THREAD

**Issue by justjacksonn** [raml-org/raml-spec#137]
This is a tracking issue, referring to this thread http://forums.raml.org/t/multiple-json-schema-for-response/712/6

The goal is to either instruct or if not yet possible, make it possible in 1.0 spec to allow some way to refer to json or xsd schema types/elements/etc within the RAML doc itself. For example, in an XSD document you can specify several types in the one file. However, in RAML you refer to the entire document. More so, XSD (and I presume JSON Schema) allow the imports/includes of other documents that can add more types. There is no way to refer to the various types for a specific element in RAML. An XSD may include several types, say users, address, phone, etc. In the RAML file, we'd want to say have a resource return just the Address type found in somedoc.xsd. In a schema: element in RAML you might want something like <name-of-schema>#<name-of-type> or something along those lines. The goal being, when parsed, the parser could identify the internal type/element referred to in the associated schema file.

In the case of creating a java SDK generator, when creating the calls to say, POST a new Address (using the above example schema doc), we'd want to generate POJOs from the XSD, which would result in Java classes like Users, User, Address, Phone, etc. We'd then want to utilize the Address POJO as a method return type (in the case of a GET or possibly POST/PUT) and allow for the Address type to be used as the body in a POST/PUT/PATCH operation. 

Currently there doesn't seem to be any way to refer to individual types/elements within a schema inside of a RAML Document, so it requires that all schemas refer to individual types and not nest multiple types in one schema doc. Maybe not a bad thing to keep it organized.. but still limiting especially for existing XSD documents in use today that have lots of includes/imports.

**Comment by lordnynex** [comment]
Hi sorry to drudge up such an old issue. I stumbled upon the forum thread looking for this functionality. 

My use case is presenting a separate response schema based on whether or not the requesting user(session) is authenticated and authorized. Effectively a private vs public view. 

I'm not sure what the best way to represent this is. I'm also skimming the json schema docs and 'required' does not seem like a fit for defining a response because the fields in question are actually optional. A more fitting description would be that the consuming application takes a separate code path if certain fields exist in the response. 

Arguably this is not the best design (something like /me would be more effective) but this is the result of adopting raml in an existing application that I can not change. 

Is there a better way to do this?

**Comment by sichvoge** [comment]
For what is your RAML being used in the end?

**Comment by sichvoge** [comment]
This is a duplicate for https://github.com/raml-org/raml-spec/issues/170. Let's keep talking using that.
