### ISSUE TITLE
Nested item's schema is never shown

### ISSUE THREAD

**Issue by vsertti** [raml-org/raml-spec#149]
`$ref` doesn't seem to be parsed by API Designer or raml2html, so the nested item's schema is never shown.
I would like to use nested schema. It does not work.

http://stackoverflow.com/questions/27055536/raml-nested-schemas

```
"type": "object",
"name": "SampleEnumerationListDto",
"properties": {
"SampleEvents": {
"type": "array",
"description": "Array of sample events",
"items": {"$ref": "SampleEventDTO" }, // I would like to see DTO here
"required": true
```

**Comment by econchick** [comment]
I'm not sure if this is a library issue with API designer/raml2html, or if it's actually a RAML specification issue.  But as an aside, for the recently-released [ramlfications](https://ramlfications.readthedocs.org) library (written in Python) this feature request is [on the horizon](https://github.com/spotify/ramlfications/issues/4) because I agree, parsing JSON `$refs` is needed.

**Comment by usarid** [comment]
Thanks Lynn, duly noted! We're working on some upcoming stuff you might be interested in, message me directly (first.last@company.com) and we can show you some of that.






On Tue, Apr 28, 2015 at 6:00 AM -0700, "Lynn Root" <notifications@github.com> wrote:












I'm not sure if this is a library issue with API designer/raml2html, or if it's actually a RAML specification issue.  But as an aside, for the recently-released ramlfications library (written in Python) this feature request is on the horizon because I agree, parsing JSON $refs is needed.

**Comment by justjacksonn** [comment]
I am working on a javascript parser for JSON Schema at the moment.. we have an internal format we use and I need to create "model" classes from JSON Schema. If any of you are doing anything related to this, I'd appreciate any collaboration, at least on the parsing process of JSON Schema.

**Comment by aldonline** [comment]
Hello everyone,
Currently the RAML parsers don't process JSON schema $refs.
In the near future we are looking to support this when the JSON schemas are referenced as external sources. Not when they are inlined, as that would require us to define a "custom" behaviour of JSON pointer when inside RAML files ( which would make the spec bigger and potentially more confusing for tool implementors ).
For now my suggestion would be to rely on externally linked JSON schemas and have some pre-processing step where you "expand" the $refs. This way you can keep your JSON schemas organized and you can eventually remove the preprocessing step when the RAML parsers learn how to do this trick.

**Comment by sichvoge** [comment]
Closing this issue with `wontfix`. Its a tooling, or parsing issue.
