### ISSUE TITLE
Eliminate formParameters (in favor of new type system)

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#180]
The unified type system allows describing form parameters in an API request body with the simplicity of the RAML 0.8 formParameters mechanism, so that mechanism is no longer needed in RAML 1.0.

**Comment by mseashor** [comment]
Got here googling for information on how to replace formParameters in RAML 1.0 (if you're upgrading from 0.8).  

This post doesn't show 'how' to replace formParameters and it wasn't immediately obvious so I'm adding a comment to address that. 

In short - you use 'properties' instead of 'formParameters' to replace formParameters inline.  You can also abstract your properties into a 'type' for reuse.  Examples below:

RAML 0.8 example
#%RAML 0.8
title: Example
/uploadFile:
  description: uploads a file with file name
  post:
    body:
      multipart/formdata:
        formParameters:
          file:
            description: the file to upload
            required: true
            type: file
          fileName:
            description: the file name
            required: false
            type: string

RAML 1.0 example
#%RAML 1.0
title: Example
/uploadFile:
  description: uploads a file with file name
  post:
    body:
      multipart/formdata:
        properties: 
          file:
            description: the file to upload
            required: true
            type: file
          fileName:
            description: the file name
            required: false
            type: string

RAML 1.0 - with an abstraction into a type
#%RAML 1.0
title: Example
types:
  fileUpload:
    properties: 
      file:
        description: the file to upload
        required: true
        type: file
      fileName:
        description: the file name
        required: false
        type: string
/uploadFile:
  description: uploads a file with file name
  post:
    body:
      multipart/formdata:
        type: fileUpload

**Comment by sichvoge** [comment]
wow - cool thanks @mseashor
