### ISSUE TITLE
Add clarification on how to validate examples against a type/schema

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#313]
RC1 does not clearly state how example/examples should be validated against their respective type/schema declaration. Examples are validated by the same rules as usual type instances with the following exceptions:

* if example is defined as string then and if the type is not a scalar type an attempt to parse it as a JSON or XML should be performed.
* even despite the fact that declaring additional unknown properties is not an error in the type system, declaring unknown properties in an example should be flagged as a warning (this rule is added to reduce amount of spelling errors).

**Comment by usarid** [comment]
I don't think this is necessary, because examples are indeed just instances of data that should be validated *exactly* as any other data, except if the `strict` flag is `false` for that example. 

If the example is defined as a string, that's nothing special -- the body of an HTTP request is also a string. The media type tells you how to parse it.

As for warnings, it's not up to the RAML spec to say that, though I agree we could suggest it -- but I don't think we should. That should be totally up to the tools provider, and it's really a matter of taste whether you want to issue warnings on perfectly valid examples that you think *might* be a typo.

**Comment by sichvoge** [comment]
OK - I'll keep that open for now to see if there are other comments, but remove it from RC2.
