### ISSUE TITLE
Support for null values

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/raml-spec#394]
It seems that RAML data types do not provide a way to allow for null-valued data in payloads, null-valued annotations, etc. 

An example of that is 
```raml
type:
  properties:
    name:
    comment:
example:
  name: Fred
  comment:
```
Here the type is object-valued with 2 required properties, `name` and `comment`, both defaulting to be of type `string`, and the example indeed gives both but `comment` has value of `null`. Since `null` is not of type `string` in YAML, it's not a valid value for this example, and there's no way to make it valid. One could use `""` (the empty string) as the value, but there should be a difference between a value that's `null` and a value that is a string of length 0. In many popular payload formats, such as JSON, there is such a difference, and RAML should be able to represent that easily. (Note also that the `required` facet only requires the key to be present, not the value to be non-null.)
 
**Proposed solution**: Lets add a `null` type to the list of built-in RAML scalar types. One would then be able to represent nullable properties as a union type of their normal type and `null` type. For the example above, one would use
```raml
type:
  properties:
    name:
    comment: string | null
example:
  name: Fred
  comment:
```

**Comment by fededonna** [comment]
I think this is not right. This is a trick just for annotations. We should do a change in the spec and say:

Values are not required in scalar annotations, so they allow an empty value in the key value node. Just for annotations.

**Comment by sichvoge** [comment]
I think that should even be more restricted to `string` only right? Since you can't really have an empty value for integer or number? For `string` that would be easier.

**Comment by fededonna** [comment]
Ok, only for strings sounds good.

**Comment by usarid** [comment]
@fededonna: I don't see why you're saying we should do something special for annotations vs introducing the `null` type and addressing the more general issue of nullable values, eg in JSON payloads.

**Comment by sichvoge** [comment]
Do you have an example @usarid? I can't think about one that would need to be set `null`.

**Comment by usarid** [comment]
JSON, for example, allows properties (or array elements) to be null; that's one of its scalar types. How do you describe a payload that can have a null in it without introducing `null` into RAML data types? For an example, see the description in this issue. Express the example in JSON if you wish.

**Comment by sichvoge** [comment]
OK, I see; missed that even JSON defines a `null` type (see http://spacetelescope.github.io/understanding-json-schema/reference/type.html)

**Comment by 3miliano** [comment]
Technically speaking _null_ is not a type, altho most languages model it as such. Null is something that came from the programming world, and has little to do with describing the shape of something. Granted that most formats such as XML or JSON carry this Null concept from the programming language in which they were implemented or designed for. 

Variables is most languages are actually references to actual values. The type usually applies to the value, but null is only a concept for references. A variable that is null, is not saying that its value is null but that it references an invalid value. Since everything is a reference in most OOP languages then it become obvious that developers started using _null_ as a marker for the absence of value. 

Then some languages splitter the concept in two. There is one marker for references and another marker for values. JavaScript uses undefined for invalid reference, and null for absence of values. Scala uses Null and None. 

My take on the matter is that we need to support both and separately. Take the following example:

```
type: object
  properties:
    firstName: string
    lastName: string
    age?: number
```

for the following JSON:

```
{ firstName: "Emiliano", lastName: "Lesende" }
```

What would be the value of age? Null? or something else? 

My recommendation goes along with what @petrochenko-pavel-a is proposing but taking it further. This two declarations are identical, one is syntactic sugar of the other:

```
type: object
  properties:
    firstName: string
    lastName: string
    age?: number
```

```
type: object
  properties:
    firstName: string
    lastName: string
    age: number | nothing
```

And the same would be for the following:

```
type: object
  properties:
    firstName: string
    lastName: string
    age: ?number # NOTE: or number? (not sure which one is better)
```

```
type: object
  properties:
    firstName: string
    lastName: string
    age: number | null
```

Of course that then you could have something like:

```
type: object
  properties:
    firstName: string
    lastName: string
    age?: ?number # NOTE: which is the equivalent of number | nothing | null
```

and that last example will validate all three of this JSONs:

```
{ firstName: "Emiliano", lastName: "Lesende" }
```

```
{ firstName: "Emiliano", lastName: "Lesende", age: null }
```

```
{ firstName: "Emiliano", lastName: "Lesende", age: 37 }
```

**Comment by usarid** [comment]
@3miliano that's effectively the approach JavaScript takes, except that in JavaScript `null` is of type `object`, but they define another type called `undefined` that literally means the key itself is not defined. 

The idea in RAML data types is that you can make a key in a map optional using the `?` suffix (or `required: false`) and that allows payloads to not have that key at all; if we want to support the key being there but with a `null` value, that's where the new `null` type comes in. So do you still feel we need `nothing` and/or we need `?number`? Your last example could just be written
```raml
type: object
  properties:
    firstName: string
    lastName: string
    age?: number | null
```
which allows `age` to be omitted, but if it's there then it forces the value to either be a number or null.

**Comment by sichvoge** [comment]
I am not really sure about the need to have a keyword `nothing` as well. We already have a "long" and "short" form being either 

```yaml
age?: number
```

or 

```
age: 
   type: number
   required: false
```

Introducing yet another would be very confusing. What I really like is the shortcut though. Being able to avoid writing `number | null` by using `number?` is very helpful.

**Comment by freddrake** [comment]
Trying to decipher this discussion. Is it agreed that there should be a ``null`` type?  (This seems necessary to model existing APIs).

I'm generally not an advocate for having both a "long form" and a "shorthand", but consistency within the specification is more important.  With a shorthand form, we end up with questions regarding what ``number | string?`` means, or whether it's allowed, or whether ``(number | string)?`` would be required instead.

**Comment by sichvoge** [comment]
I guess the combinations you would have without using `?` anyways. So I'd say your examples would translate to something like the following:

`number | string?` -> `number | (string | null)` 

`(number | string)?` -> `(number | string) | null`

@petrochenko-pavel-a @usarid is that right?

**Comment by usarid** [comment]
It is right, and of course then you see that both amount to exactly the same thing.

**Comment by freddrake** [comment]
Sounds good to me.

Do you mean to imply that the answer to my initial question is "Yes, there will be a ``null`` type"?

**Comment by sichvoge** [comment]
That is what we discuss here ;) So far it seems that there isn't a compelling reason why shouldn't.

**Comment by 3miliano** [comment]
I just suggested the add of ​_nothing_​ so there is uniformity between how we handle null and absence, and then suggested the question mark because it is tedious to define `x | null` or `x | nothing`. Having it on the key rather than the type of the value is fine since RAML cannot represent function types, if it did then I would advocate for ​_nothing_​ a lot more strongly since for function type definition is a must.

**Comment by julianesevich** [comment]
Just summarizing and checking my understanding in which I base my agreement...

We are adding a Null scalar type so that following type definitions are valid, and each example value is a different value. 

types:
    Email:
        type: object
        properties:
            name:
                type: string

    User1:
        type: object
        properties:
            name:
                type: string
            emails:
                type: Email[]
                required: false
        example:
            name: "Name"

    User2:
        type: object
        properties:
            name:
                type: string
            emails:
                type: Email[]| Null
        example:
            name: "Name"
            emails:

    User3:
        type: object
        properties:
            name:
                type: string
            emails:
                type: (Email| Null)[]
        example:
            name: "Name"
            emails: [null]

We are also considering addition of syntax sugar for each case, such as:

    User1:
        type: object
        properties:
            name: string
            emails?: Email[]

    User2:
        type: object
        properties:
            name: string
            emails: Email[]?

    User3:
        type: object
        properties:
            name: string
            emails: Email?[]

**Comment by usarid** [comment]
Exactly right, except all lowercase: `null`.

This is now an official decision. Thanks everyone!

**Comment by usarid** [comment]
It occurs to me that we actually still need to clarify how `null` applies to contexts where the data is inherently strings: query parameters and the query string, headers, and URI parameters. For example, how should RAML handle:

```raml
headers:
  dept-code:
    type: number | null
    examples:
      specific-department:
        value: 1200
      no-department:
        value:
```

Across the wire, in HTTP land, if no department is specified, should the (always string-valued) value of dept-code be the empty string ("") or the string "null"? Of course this RAML could be a lot more explicit about it, and not use null, though it would take a bit more work:
```raml
types:
  null-header-1:
    type: string
    enum: [ "" ]
  null-header-2:
    type: string
    enum: [ "null" ]
headers:
  dept-code:
    type: number | null-header-1 | null-header-2
    examples:
      specific-department:
        value: 1200
      no-department-variant-1:
        value: ""
      no-department-variant-2:
        value: "null"
```
Note that in many cases there isn't a need for this anyway, e.g. if the value is already of type `string`:
```raml
headers:
  dept-code:
    type: string
    examples:
      specific-department:
        value: "1200"
      no-department-variant-1:
        value: ""
      no-department-variant-2:
        value: "null"
```

But we still need to decide what to do with `null` itself in these inherently string-valued contexts, i.e. what serialization rule applies. I tend to think we should specify explicitly that `null` validates only against the 4-character string "null". Here's some validation that this may be a reasonable pattern: https://wiki.mozilla.org/Security/Origin#Selection_of_.22null.22_token

**Comment by freddrake** [comment]
I would think that ``null`` can't be serialized in the query string or headers, unless another layer of encoding is applied (such as a header with a JSON-encoded payload).

Is it interesting to transmit a null value in a header or query string?  I'd expect most apps would deal with mapping missing or empty values within the application code, so the RAML would deal with specifying whether the query parameter or header can be omitted or given an empty value.

**Comment by petrochenko-pavel-a** [comment]
>I would think that null can't be serialized in the query string or headers, unless another layer of 
agree.

according to:
```
headers:
  dept-code:
    type: number | null
    examples:
      specific-department:
        value: 1200
      no-department:
        value:
```

my understanding is that in this case 
```
no-department:
        value:
```
has value of `null` and it should pass validation

**Comment by freddrake** [comment]
I *do* understand that's the type being described.  The question is whether that serialization can really happen.  Consider:

~~~~~~
dept-code:
  type: string | null
  examples:
    specific-department:
      value: "sales"
    no-department:
      value: ""
    unspecified:
      value:
~~~~~~

How would you expect that unspecified example to look as a header?

**Comment by usarid** [comment]
I would expect it to be `null` when expressed in YAML and so I'm proposing it would like like `dept-code null`over the wire, i.e. The value would be the string "null".

**Comment by petrochenko-pavel-a** [comment]
>The value would be the string "null".

That's fine, but on other side, do you expect string "null" to pass validation against `null` type?

**Comment by julianesevich** [comment]
Just to add some more info for discussion, since I do not have a position set.

If we consider null as a non scalar type, considering union of non-scalar as a union involving at least one non scalar type,
then applies specified restrictions for object, union of non-scalar or a type expression involving them.

for headers
- validation is not defined by RAML
- MAY default to treating the format of the header value as JSON in applying the type to instances of that header
- MAY allow other treatments based on annotations

for query parameters
- MUST default to treating the format of the query parameter value as JSON in applying the type to instances of that query parameter.
- MAY allow other treatments based on annotations.

In that case, the literal null as JSON representation for null would be HTTP value.

We could also recommend using a media type annotation as 'application/json' on the header.

A question: in union of scalars such as type (boolean | string), how do we ensure serialization rule is not ambiguous for a header http value false, for example, or in case of ambiguous value we use declaration order.

We should also consider if the use case is recommended beyond being specified.

Consistency with common http programming apis where null means the absence of header or parameter, would involve an extra check for disambiguation.

**Comment by freddrake** [comment]
Looking back over the current raml-10.md, I worry about this paragraph:

> If a header declaration specifies an object type or a union of non-scalar
> types for the value of the header, or if it specifies an array type for the
> value of the header and the underlying type of the array is an object or
> array type or a union of non-scalar types, then validation is not defined
> by RAML; processors MAY default to treating the format of the header
> value as JSON in applying the type to instances of that header, or they
> MAY allow other treatments based on annotations.

The client is affected by whether the server is handling the headers as JSON or not.  Also, this suggests ``null`` isn't being treated as a scalar value if this header construct is interpreted as providing a ``null`` value (referring to our earlier definition of the ``dept-code`` header):

~~~~~
Dept-Code: null
~~~~~

Perhaps header decoding needs to be specifically stated rather than sticking with the current discretionary language.  Making the default be "it's a string" and requiring anything else to be explicit would certainly make sense and make it very clear how request data will be interpreted.

The same considerations apply to the query string as well.

**Comment by usarid** [comment]
@freddrake:

>The client is affected by whether the server is handling the headers as JSON or not.
It's basically up to the server to determine how it's handling the headers; it's told the client type information about them, but it has not told the client how to serialize/deserialize them, because there is no mechanism in HTTP to tell that, as there is (media type) for bodies.

>Perhaps header decoding needs to be specifically stated... requiring anything else to be explicit would certainly make sense and make it very clear how request data will be interpreted.

The question is how. It's not part of HTTP, which just says the headers are strings (same holds for bodies) without saying anything about their formats. We could attack that in various ways, e.g. creating a facet called something like `mediaType` on the type declaration that gives you a default way to interpret values when they are not in a context (HTTP bodies) that already gives you a media type, or defaulting to the same media type that the body is using. It just seemed overkill for headers and certainly for URI parameters. Alternatively, we could just disallow anything but scalars to be used in declaring headers and URI parameters, which would certainly be explicit, but it would also mean there would be no way to use a combination of annotations and types if an API did want to transmit more structured data via a header. And while it's rare to transmit structured information in headers and even rarer to do so in URI parameters, it's not so rare in the query parameters, I would guess, so perhaps we should leave that possibility there. I don't like the non-explicitness either, but I'm also not crazy about the complexity of adding yet more metadata for these seemingly corner cases.

Which is a long way of saying that I'm not sure what the best way forward is...

**Comment by usarid** [comment]
Also, @freddrake:
>the RAML would deal with specifying whether the query parameter or header can be omitted or given an empty value.

The question is how do you define "given an empty value". Let's assume for the moment that `null` is to be treated as a scalar in RAML (we haven't been explicit about that and we need to make a call here). It's easy to take a decision that a RAML will allow the header value "" by the type allowing a string of length 0, and that it will allow the header value "null" by the type allowing a `null`. But as @petrochenko-pavel-a noted, it's not so easy to say what happens when you receive a header with a value "null" and want to deserialize it: if its type only allowed `null` you could just say "hey, I bet this is a `null` and not an invalid string of length 4"; but what if its type is `string | null`? Do you deserialize it as the string "null" or the null-type scalar?

**Comment by usarid** [comment]
@julianesevich also anticipated some of these directions in his response. For disambiguating the same case @petrochenko-pavel-a mentioned, i.e. getting a "null" in a header and needing to deserialize it against a type of `string | null`, or getting a "false" in a header and needing to deserialize it against a type of `boolean | string`, he suggests:

>in case of ambiguous value we use declaration order

That's certainly one way, basically having the first matching declaration take precedence in deserializing. It would mean that `boolean | string` is not identical to `string | boolean` as a type declaration. But there's a certain elegance to it in that it parallels the way we apply e.g. multiple traits in the order they're specified, or in the way routing rules usually work, or in the way programming languages usually handle boolean expressions (evaluating left to right only until the answer is known and then stopping evaluation), etc.

**Comment by usarid** [comment]
OK, then the proposal is 

1. to treat `null` as a scalar type (like `string`, `number`, `boolean`, etc)
2. in a RAML context that requires *values* of type `null` (vs just type declarations), the usual YAML `null` is used, e.g. when the type is `number | null` you may use `enum: [ 1, 2, ~ ]` or more explicitly/verbosely `enum: [ 1, 2, !!null "" ]`; in non-inline notation you can just omit the value completely, of course.
3. for headers, URI parameters, and query parameters, only the string value "null" (case-sensitive) validates against the `null` type, and in turn the string value "null" (case-sensitive) deserializes to the `null` type.

More generally (not just for nulls) we need to deal with disambiguation of deserialization for headers, URI parameters, and query parameters, so the proposal is

1. to deserialize an instance of data against a type that has unions in it, first fully expand all unions at every level, then match the instance against each element in that expansion starting from the left-most and proceeding to the right; use the first successful matching element to deserialize the instance; and if no elements match, the instance is invalid.

**Comment by sichvoge** [comment]
Sounds reasonable to me. The part about deserialization, is that not already clear from how you validate union types against instances in general? Not sure what the differences are to headers, URI parameters, and query parameters. Can you elaborate more?

**Comment by freddrake** [comment]
While I'm pretty uncomfortable with attempting to encode non-scalar values in a header or query parameter (aside from arrays of scalars in a collection of headers or complete query string), I can understand how this would be applied given a concrete request.

I don't find decoding a complex (application) query string from a single (request) query parameter a compelling use case. Interesting query languages are generally passed along as a string payload and are turned over to specialized parsers for interpretation, and RAML should support that case, but need not provide a new solution to decoding such (application) query strings. I'm thinking of Solr queries and SQL SELECT statements are real-world examples; there are many similar query languages.

These "interesting" query languages really require specialized handling by applications.  There are query languages that can be encoded in JSON, XML, or other structured forms, but those aren't normally handled in query parameters, but in POST bodies.

**Comment by petrochenko-pavel-a** [comment]
>The part about deserialization, is that not already clear from how you validate union types against instances in general?
you just need to ensure that at least one option passes. 

>Not sure what the differences are to headers, URI parameters, and query parameters
I actually see no differences validation algorithm itself.

**Comment by petrochenko-pavel-a** [comment]
>to deserialize an instance of data against a type that has unions in it, first fully expand all unions at >every level, then match the instance against each element in that expansion starting from the left-most >and proceeding to the right; use the first successful matching element to deserialize the instance; and if >no elements match, the instance is invalid.

Sounds reasonable.

**Comment by julianesevich** [comment]
Have some doubts regarding disambiguation on deserialization.
The rule for unions using textual order works well in general but in the specific case of null as the absence of defined value
that might be better considered as out of band (escaping null string required?).

for example having with dept-code defined as

    dept-code: (string | null)

Having

    dept-code: null

over the wire

I would expect to retrieve null.

I've noted there is [no support for null in swagger and in openAPI](https://github.com/OAI/OpenAPI-Specification/issues/229.There is some tension between the require of community for their use cases and the backward compatibility with swagger. More over when null is a primitve type in json schema.

**Comment by usarid** [comment]
The fact that null isn't supported by swagger is a drawback of swagger - I think that community recognizes it as such.

>I would expect to retrieve null instead of "null"

Probably true, because we're human. You can achieve it, of course, with `null | string`, and in general it's usually better to specify unions from more specific to less specific so this would be preferred, but I agree most won't think about it. Then again, most headers and query parameters don't need to use nulls, so we're talking corner cases anyway. I'm not so concerned.

But... should we define `(...)?` as `null | (...)` vs as `(...) | null`? It should make it more likely for people to achieve the right behavior, for string-based values.

It feels like that's the last decision to make in this proposal before we wrap it up.

**Comment by sichvoge** [comment]
Agree, in string-valued contexts `null | (...)` makes more sense when you validate a union from left to right.

**Comment by usarid** [comment]
OK, so here's the decision, wrapping up all the above:

1. treat `null` as a scalar type (like `string`, `number`, `boolean`, etc)
2. in a RAML context that requires *values* of type `null` (vs just type declarations), the usual YAML `null` is used, e.g. when the type is `number | null` you may use `enum: [ 1, 2, ~ ]` or more explicitly/verbosely `enum: [ 1, 2, !!null "" ]`; in non-inline notation you can just omit the value completely, of course.
3. for headers, URI parameters, and query parameters, only the string value "null" (case-sensitive) validates against the `null` type, and in turn the string value "null" (case-sensitive) deserializes to the `null` type.
4. The shortcut type expression `x?` means `null | x`

More generally (not just for nulls) we need to deal with disambiguation of deserialization for headers, URI parameters, and query parameters, so the decision is

1. to deserialize an instance of data against a type that has unions in it, first fully expand all unions at every level, then match the instance against each element in that expansion starting from the left-most and proceeding to the right; use the first successful matching element to deserialize the instance; and if no elements match, the instance is invalid.

**Comment by svacas** [comment]
regarding assertion # 3, shouldn't also a blank header or query-param of a non-string scalar type validate against null?

**Comment by usarid** [comment]
I suppose we could choose what we want, but the choice of "null" is more prescriptive and less likely to be unintended, it seems - otherwise you should accept an empty string directly.

**Comment by JohnMcAvinue** [comment]
I have my RAML document littered with "nil" references because this is how I was told (on here) to allow a property to be nullable. E.g:

```
  numberOfCustomFields:
    type: number
    format: int32 | nil
    description: The count of custom fields for this job
```
I have updated to the latest versions of Atom and Workbench and now have errors everywhere I try this:

"_Following format values are allowed: int32,int64,int,long,float,double,int16,int8_"

I have tried to follow the above conversation but there's a lot of suggestions going on. I need to be able to define a nullable integer on my API.

**Comment by petrochenko-pavel-a** [comment]
Hi John, to best of my understanding nullable integer will be.
```raml
numberOfCustomFields:
    type: number | nil
    format: int32 
    description: The count of custom fields for this job
```


Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
@sichvoge , What about
>The shortcut type expression x? means null | x

Spec misses it, but it actually looks as a very handy shortcut for nullable types.

Regards,
Pavel

**Comment by sichvoge** [comment]
Its not really missing (see image below) but I get what you experience. We should be more clear about that.

![image](https://cloud.githubusercontent.com/assets/498114/18748946/f60c5984-80d4-11e6-8876-b9b826a8fb78.png)

**Comment by JohnMcAvinue** [comment]
Thanks for replying. So we describe the nullable data types as object and use a comment to say it's an int or nil? Is that the official approach?

**Comment by petrochenko-pavel-a** [comment]
nope, 
`type: number | nil` or alternatively `type: number?`

Regards,
Pavel

**Comment by JohnMcAvinue** [comment]
Thanks but that prevents me from specifying the format of the number, be it int or decimal etc. I get this error message:

_"format facet can only be used with [number,integer,datetime] types"_

**Comment by petrochenko-pavel-a** [comment]
hm, thats fun, in fact `nil` type should allow application of any facets. 

Regards,
Pavel

**Comment by freddrake** [comment]
The documentation for ``format`` seems confused.  The name suggests this is a presentation hint, but the allowed values suggest this specializes the type (for ``number``).  For date, time, and datetime values, ``format`` plays a more necessary role in how the values is serialized for interchange (in JSON, etc.).

``format`` for the ``number`` type makes me want to run away screaming.
