### ISSUE TITLE
Overlays and extensions should be applied after expansion

### ISSUE THREAD

**Issue by nialdarbey** [raml-org/raml-spec#488]
The[ restrictions on Overlays](https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#overlays) are too tight. As stated:

> The behavior-invariance restrictions of an overlay are defined as follows: after applying the merging algorithm and before applying any inheritances of types, resource types, traits, and annotation types, the tree of nodes in the merged document is compared with the tree of nodes in the master RAML document after resolving all !include tags. Any differences in the documents MUST be only in the nodes listed in the following table.

This means that Overlays are of no real benefit to me. I habitually use resource types. I habitually parameterize these with _resourcePathName_ in order to resolve the types in the requests and responses. 

Please change the parsing rules so that Overlays are applied AFTER expansion.

Overlays represent a very attractive form of revisiting different parts of the full API definitions (after expansion) and enhancing it with annotation information for client developers.

**Comment by usarid** [comment]
After discussions with Nial, it's clear that this should apply to extensions just the same as overlays, so changing the title.

**Comment by usarid** [comment]
The way Nial is thinking about it is compelling: I have a carefully-crafted API, with externalized reusable traits and types and such, and it works. Then I add extra metadata to it for some reason: maybe it's for a particular tool that requires annotations, maybe it's for translating the docs to a different language. I should be able to overlay the entire API, without caring about what came from an `!include` and what came from a trait. In fact, somebody should be able to refactor the API spec to change the `!include`s and such, and as long as the final spec is unchanged, the overlays and extensions should continue to work as is.

I'm having a hard time seeing how we can live with the algorithm as originally described. Basically, when users are creating solid libraries of reusable types, traits, and resource types, their master RAML files will consist of resources and maybe not much else, so overlays would simply not work.

Let's see if this survives the reality test: In reality, they may end up reconstructing parts of the deeper RAML tree anyway, to add examples specific to their API, and once a part of the RAML tree is in the master file, you can overlay it. So does that mean we don't really have this problem? No, that is clearly very hacky: you cannot rely on that tree being there whenever you need to overlay it, and you don't want to modify the master RAML file just to allow others to overlay it.

Moreover, this completely kills the ability for 3rd parties to provide overlays to RAML specifications, because the 3rd party providers shouldn't have to care at all what is the way the RAML comes together (what is externalized, reused, etc)

It feels like we have to correct the algorithm in the spec to say that overlays and extensions are applied after the RAML is fully resolved. They should be truly external to the master RAML spec.
